CREATE TABLE schedule (
    SCHEDULE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    WRITER VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    MODIFIED_AT DATETIME NOT NULL
);
